Apply rabbit's suggestion

diff --git a/.github/workflows/run-fuzz-tests.yaml b/.github/workflows/run-fuzz-tests.yaml
--- a/.github/workflows/run-fuzz-tests.yaml
+++ b/.github/workflows/run-fuzz-tests.yaml
@@ -83,7 +83,12 @@ jobs:
         env:
           PGPASSWORD: nest_user_fuzz_password
         run: |
-          pg_restore -h localhost -U nest_user_fuzz -d nest_db_fuzz < backend/data/nest.dump
+          set -euo pipefail
+          if ! pg_restore -h localhost -U nest_user_fuzz -d nest_db_fuzz < backend/data/nest.dump; then
+            echo "Data loading failed"
+            exit 1
+          fi
+          echo "Data loading completed."
 
       - name: Build Fuzz-testing image
         uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
